### ISSUE TITLE
2.x stable roadmap

### ISSUE THREAD

**Issue by satya164** [react-navigation/stack#162]
- [ ] ~Fix issues in react-native-screens (in progress https://github.com/kmagiera/react-native-screens/pull/130)~
- [ ] Fix perf issues in react-native-reanimated (this might fix it https://github.com/kmagiera/react-native-reanimated/pull/354)
- [x] Implement theming
- [x] Remove usage of `MaskedViewIOS` by default and allow user to specify it
- [x] Update documentation (in progress https://github.com/react-navigation/react-navigation.github.io/pull/454)
- [x] Fix issues with safe area context

cc @brentvatne @osdnk @janicduplessis

**Comment by brentvatne** [comment]
for `MaskedViewIOS` - we could maybe depend on https://github.com/react-native-community/react-native-masked-view in @react-navigation/native, but not require people to link it unless they try to use the uikit style header

**Comment by kesha-antonov** [comment]
Hey
What's the perf issues in RN-reanimated?

**Comment by satya164** [comment]
@kesha-antonov the one you encountered

**Comment by kesha-antonov** [comment]
@satya164 in release more its much faster

**Comment by kesha-antonov** [comment]
Touchables https://kmagiera.github.io/react-native-gesture-handler/docs/component-touchables.html
and Buttons https://kmagiera.github.io/react-native-gesture-handler/docs/component-buttons.html
improved perf a bit for me

**Comment by osdnk** [comment]
@satya164 please include this last issue we mentioned in this roadmap. It's probably the last thing :)

**Comment by osdnk** [comment]
cc @kesha-antonov

**Comment by kesha-antonov** [comment]
Would be good

**Comment by vernondegoede** [comment]
Why is this issue called `2x roadmap`, while the NPM packages that are currently in `alpha` are in the `5.x` version range?

**Comment by brentvatne** [comment]
@vernondegoede - that is a different package, published from https://github.com/react-navigation/navigation-ex, for integration with the react-navigation@5 api

**Comment by marcelschulze** [comment]
Does 2.0 fixes this: https://github.com/react-navigation/stack/issues/139 ?
Or the other one of navigation-ex?

**Comment by satya164** [comment]
@marcelschulze both implement animations for all state changes including reset

**Comment by satya164** [comment]
https://github.com/react-navigation/stack/releases/tag/v2.0.1
